# This workflow automatically fetches the top 10 trending anime from the Jikan API,
# updates the README.md file, and archives a copy of the README on a daily schedule.

name: Update Trending Anime List

on:
  schedule:
    # Runs at 00:30 UTC (6:00 AM IST) and 12:30 UTC (6:00 PM IST).
    - cron: '30 0 * * *'
    - cron: '30 12 * * *'
  workflow_dispatch:

jobs:
  update_readme_with_anime:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out your repository's code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Fetch Top 10 Trending Anime and Format List
      # This step creates the header, adds a timestamp, then appends the formatted list.
      - name: Fetch and Format Anime List
        run: |
          echo "### 📈 Top 10 Trending Anime" > ANIME_LIST.md
          echo "" >> ANIME_LIST.md
          echo "*Last updated on: $(TZ='Asia/Kolkata' date)*" >> ANIME_LIST.md
          echo "" >> ANIME_LIST.md
          curl -s "https://api.jikan.moe/v4/top/anime?filter=airing&limit=10" \
          | jq -r '.data | map("\(.rank). [\(.title)](https://myanimelist.net/anime/\(.mal_id)) - Score: \(.score // "N/A")") | join("\n")' \
          >> ANIME_LIST.md

      # Step 3: Update the README.md file with the new list
      # This uses a more robust Python script to replace the content between the markers.
      - name: Update README
        run: |
          python -c "
          import re
          
          # Read the content from the new anime list file
          with open('ANIME_LIST.md', 'r') as f:
              anime_list_content = f.read()
          
          # Read the content of the README file
          with open('README.md', 'r') as f:
              readme_content = f.read()

          # Define the replacement block using an f-string for clarity
          replacement = f'<!-- ANIME_LIST_START -->\\n{anime_list_content}\\n<!-- ANIME_LIST_END -->'
          
          # Use re.DOTALL to make '.' match newlines, which is more reliable
          new_readme_content = re.sub(
              r'<!-- ANIME_LIST_START -->.*?<!-- ANIME_LIST_END -->',
              replacement,
              readme_content,
              flags=re.DOTALL
          )
          
          # Write the updated content back to the README file
          with open('README.md', 'w') as f:
              f.write(new_readme_content)
          "

      # Step 4: Archive the updated README file
      # This step creates an 'archive' directory and copies the updated README into it
      # with a timestamped filename.
      - name: Archive updated README
        run: |
          mkdir -p archive
          TIMESTAMP=$(TZ='Asia/Kolkata' date +'%Y-%m-%d_%H-%M-%S')
          cp README.md archive/$TIMESTAMP.md

      # Step 5: Commit and Push the changes
      # This will commit both the updated README and the new archive file.
      - name: Commit and Push changes
        run: |
          # This configures git to use your GitHub username and a no-reply email
          # so the commit is attributed to your profile.
          git config --global user.name '${{ github.actor }}'
          git config --global user.email '${{ github.actor }}@users.noreply.github.com'
          
          # Add, commit, and push only if there are changes
          if [[ -n $(git status -s) ]]; then
            git add .
            git commit -m "Automated update: Top 10 trending anime"
            git push https://${{ secrets.ACTION_PAT }}@github.com/${{ github.repository }}.git HEAD:main
          else
            echo "No changes to commit."
          fi
